Change string to DU
fable-compiler/repl pull request #118
Opened 2020-10-06 19:00 UTC by awf

When viewing this sample, I thought it might be nice to remove the "_" match on (old) line 176.  To do so, I thought it might be nicer to use a discriminated union instead of strings to indicate state.  Hence this PR -- I hope you like it :)  All comments very much welcome -- I am a distinct newbie.

2020-10-06 21:09 UTC, MangelMaxime requested changes

2020-10-06 21:09 UTC, MangelMaxime commented on public/samples/elmish/todomvc.fs
> +    |Completed -> "Completed"
Missing a space after `|`

2020-10-07 08:03 UTC, awf commented on public/samples/elmish/todomvc.fs
> +    |Completed -> "Completed"
Fixed, thanks!

2020-10-15 10:14 UTC, awf commented
@cgravill called this "moving from string typing to strong typing", which I found very amusing.

2020-10-15 10:42 UTC, cgravill commented
I've found a lot of incidental programmers much happier with F#/Fable (than JavaScript) once we started using more typing features. Combined with the excellent Elm(ish) approach it lets them concentrate on mapping domain types to a visualisation without worrying they're breaking the infrastructure programming.

2020-10-15 11:51 UTC, alfonsogarciacaro commented
Sorry, missed the notification! This is a good change, I think the string remained from the original React example we converted. Thank you!

2020-10-15 11:51 UTC, merged

2020-10-15 12:19 UTC, awf commented
Thanks!